[project]
name = "paper_crawler"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "playwright>=1.49.0",
]

[dependency-groups]
dev = [
    "pytest-playwright>=0.6.2",
]
